# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1dmirqsyV-CTxAdQQU6b2SmzemG1mZC
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-V2')
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1,embedding2)
print("\n similarity score:",round(float(similarity),2))
if similarity>0.75:
  print("similarity level:high")
elif similarity>0.4:
  print("similarity level:medium")
else:
  print("similarity level:low")